drop table anmeldung_tagesschule_zeitabschnitt_aud;
drop table anmeldung_tagesschule_zeitabschnitt;

alter table anmeldung_tagesschule_zeitabschnitt
	drop foreign key FK_anmeldung_tagesschule_id;

alter table anmeldung_tagesschule_aud
	drop foreign key FK_anmeldung_tagesschule_aud_revinfo;
