-- Adresse Bern
INSERT INTO adresse(id,
					timestamp_erstellt,
					timestamp_mutiert,
					user_erstellt,
					user_mutiert,
					version,
					vorgaenger_id,
					gueltig_ab,
					gueltig_bis,
					gemeinde,
					hausnummer,
					land,
					organisation,
					ort,
					plz,
					strasse,
					zusatzzeile)
VALUES (UUID(),
		'2018-10-23 00:00:00',
		'2018-10-23 00:00:00',
		'flyway',
		'flyway',
		0,
		NULL,
		'2018-01-01 00:00:00',
		'9999-01-01 00:00:00',
		'BERN',
		'5',
		'CH',
		NULL,
		'Bern',
		'3001',
		'Predigergasse',
		NULL);

-- Adrian Schuler Default TS Benutzer Bern
INSERT INTO benutzer(id,
					 timestamp_erstellt,
					 timestamp_mutiert,
					 user_erstellt,
					 user_mutiert,
					 version,
					 vorgaenger_id,
					 email,
					 nachname,
					 username,
					 vorname,
					 mandant_id,
					 externaluuid,
					 status)
VALUES (UUID(),
		'2018-10-23 00:00:00',
		'2018-10-23 00:00:00',
		'flyway',
		'flyway',
		0,
		NULL,
		'adrian.schuler@example.com',
		'Schuler',
		'scad',
		'Adrian',
		'e3736eb8-6eef-40ef-9e52-96ab48d8f220',
		NULL,
		'AKTIV');

INSERT INTO berechtigung(id,
						 timestamp_erstellt,
						 timestamp_mutiert,
						 user_erstellt,
						 user_mutiert,
						 version,
						 vorgaenger_id,
						 gueltig_ab,
						 gueltig_bis,
						 role,
						 benutzer_id,
						 institution_id,
						 traegerschaft_id)
	(
	SELECT UUID(),
		   '2018-10-23 00:00:00',
		   '2018-10-23 00:00:00',
		   'flyway',
		   'flyway',
		   0,
		   NULL,
		   '2018-01-01 00:00:00',
		   '9999-01-01 00:00:00',
		   'ADMIN_TS',
		   benutzer.id,
		   NULL,
		   NULL
	FROM benutzer
	WHERE username = 'scad');

-- Kurt Blaser Default BG Benutzer Bern
INSERT INTO benutzer(id,
					 timestamp_erstellt,
					 timestamp_mutiert,
					 user_erstellt,
					 user_mutiert,
					 version,
					 vorgaenger_id,
					 email,
					 nachname,
					 username,
					 vorname,
					 mandant_id,
					 externaluuid,
					 status)
VALUES (UUID(),
		'2018-10-23 00:00:00',
		'2018-10-23 00:00:00',
		'flyway',
		'flyway',
		0,
		NULL,
		'kurt.blaser@example.com',
		'Blaser',
		'blku',
		'Kurt',
		'e3736eb8-6eef-40ef-9e52-96ab48d8f220',
		NULL,
		'AKTIV');

INSERT INTO berechtigung(id,
						 timestamp_erstellt,
						 timestamp_mutiert,
						 user_erstellt,
						 user_mutiert,
						 version,
						 vorgaenger_id,
						 gueltig_ab,
						 gueltig_bis,
						 role,
						 benutzer_id,
						 institution_id,
						 traegerschaft_id)
	(
	SELECT UUID(),
		   '2018-10-23 00:00:00',
		   '2018-10-23 00:00:00',
		   'flyway',
		   'flyway',
		   0,
		   NULL,
		   '2018-01-01 00:00:00',
		   '9999-01-01 00:00:00',
		   'ADMIN_BG',
		   benutzer.id,
		   NULL,
		   NULL
	FROM benutzer
	WHERE username = 'blku');


INSERT INTO gemeinde_stammdaten(id,
								timestamp_erstellt,
								timestamp_mutiert,
								user_erstellt,
								user_mutiert,
								version,
								default_benutzerbg_id,
								default_benutzerts_id,
								gemeinde_id,
								adresse_id,
								mail,
								telefon,
								webseite,
								beschwerde_adresse_id,
								keine_beschwerde_adresse,
								korrespondenzsprache,
								logo_content)
	(
	SELECT UUID(),
		   '2018-10-23 00:00:00',
		   '2018-10-23 00:00:00',
		   'flyway',
		   'flyway',
		   0,
		   benutzer_bg.id,
		   benutzer_ts.id,
		   'ea02b313-e7c3-4b26-9ef7-e413f4046db2',
		   adresse.id,
		   'bss@bern.ch',
		   '+41 31 321 61 11',
		   'https://www.bern.ch',
		   NULL,
		   TRUE,
		   'DE_FR',
		   NULL
	FROM adresse adresse
		 LEFT JOIN benutzer benutzer_ts ON benutzer_ts.vorname = 'Adrian' AND benutzer_ts.nachname = 'Schuler'
		 LEFT JOIN benutzer benutzer_bg ON benutzer_bg.vorname = 'Kurt' AND benutzer_bg.nachname = 'Blaser'
	WHERE strasse = 'Predigergasse' AND plz = '3001' AND hausnummer = '5'
	LIMIT 1);

-- Adresse Ostermundigen
INSERT INTO adresse(id,
					timestamp_erstellt,
					timestamp_mutiert,
					user_erstellt,
					user_mutiert,
					version,
					vorgaenger_id,
					gueltig_ab,
					gueltig_bis,
					gemeinde,
					hausnummer,
					land,
					organisation,
					ort,
					plz,
					strasse,
					zusatzzeile)
VALUES (UUID(),
		'2018-10-23 00:00:00',
		'2018-10-23 00:00:00',
		'flyway',
		'flyway',
		0,
		NULL,
		'2018-01-01 00:00:00',
		'9999-01-01 00:00:00',
		'OSTERMUNDIGEN',
		'1',
		'CH',
		NULL,
		'Ostermundigen',
		'3072',
		'Schiessplatzweg',
		NULL);

-- Kurt Schmid Default BG Benutzer Ostermundigen
INSERT INTO benutzer(id,
					 timestamp_erstellt,
					 timestamp_mutiert,
					 user_erstellt,
					 user_mutiert,
					 version,
					 vorgaenger_id,
					 email,
					 nachname,
					 username,
					 vorname,
					 mandant_id,
					 externaluuid,
					 status)
VALUES (UUID(),
		'2018-10-23 00:00:00',
		'2018-10-23 00:00:00',
		'flyway',
		'flyway',
		0,
		NULL,
		'kurt.schmid@example.com',
		'Schmid',
		'scku',
		'Kurt',
		'e3736eb8-6eef-40ef-9e52-96ab48d8f220',
		NULL,
		'AKTIV');

INSERT INTO berechtigung(id,
						 timestamp_erstellt,
						 timestamp_mutiert,
						 user_erstellt,
						 user_mutiert,
						 version,
						 vorgaenger_id,
						 gueltig_ab,
						 gueltig_bis,
						 role,
						 benutzer_id,
						 institution_id,
						 traegerschaft_id)
	(
	SELECT UUID(),
		   '2018-10-23 00:00:00',
		   '2018-10-23 00:00:00',
		   'flyway',
		   'flyway',
		   0,
		   NULL,
		   '2018-01-01 00:00:00',
		   '9999-01-01 00:00:00',
		   'ADMIN_BG',
		   benutzer.id,
		   NULL,
		   NULL
	FROM benutzer
	WHERE username = 'scku');

-- Adrian Huber Default TS Benutzer Ostermundigen
INSERT INTO benutzer(id,
					 timestamp_erstellt,
					 timestamp_mutiert,
					 user_erstellt,
					 user_mutiert,
					 version,
					 vorgaenger_id,
					 email,
					 nachname,
					 username,
					 vorname,
					 mandant_id,
					 externaluuid,
					 status)
VALUES (UUID(),
		'2018-10-23 00:00:00',
		'2018-10-23 00:00:00',
		'flyway',
		'flyway',
		0,
		NULL,
		'adrian.huber@example.com',
		'Huber',
		'huad',
		'Adrian',
		'e3736eb8-6eef-40ef-9e52-96ab48d8f220',
		NULL,
		'AKTIV');

INSERT INTO berechtigung(id,
						 timestamp_erstellt,
						 timestamp_mutiert,
						 user_erstellt,
						 user_mutiert,
						 version,
						 vorgaenger_id,
						 gueltig_ab,
						 gueltig_bis,
						 role,
						 benutzer_id,
						 institution_id,
						 traegerschaft_id)
	(
	SELECT UUID(),
		   '2018-10-23 00:00:00',
		   '2018-10-23 00:00:00',
		   'flyway',
		   'flyway',
		   0,
		   NULL,
		   '2018-01-01 00:00:00',
		   '9999-01-01 00:00:00',
		   'ADMIN_TS',
		   benutzer.id,
		   NULL,
		   NULL
	FROM benutzer benutzer
	WHERE benutzer.username = 'huad');

INSERT INTO gemeinde_stammdaten(id,
								timestamp_erstellt,
								timestamp_mutiert,
								user_erstellt,
								user_mutiert,
								version,
								default_benutzerbg_id,
								default_benutzerts_id,
								gemeinde_id,
								adresse_id,
								mail,
								telefon,
								webseite,
								beschwerde_adresse_id,
								keine_beschwerde_adresse,
								korrespondenzsprache,
								logo_content)
	(
	SELECT UUID(),
		   '2018-10-23 00:00:00',
		   '2018-10-23 00:00:00',
		   'flyway',
		   'flyway',
		   0,
		   benutzer_bg.id,
		   benutzer_ts.id,
		   '80a8e496-b73c-4a4a-a163-a0b2caf76487',
		   adresse.id,
		   'info@ostermundigen.ch',
		   '+41 31 930 14 14',
		   'https://www.ostermundigen.ch',
		   NULL,
		   TRUE,
		   'DE',
		   NULL
	FROM adresse adresse
		 LEFT JOIN benutzer benutzer_ts ON benutzer_ts.vorname = 'Adrian' AND benutzer_ts.nachname = 'Huber'
		 LEFT JOIN benutzer benutzer_bg ON benutzer_bg.vorname = 'Kurt' AND benutzer_bg.nachname = 'Schmid'
	WHERE strasse = 'Schiessplatzweg' AND plz = '3072' AND hausnummer = '1'
	LIMIT 1);

DELETE
FROM application_property
WHERE name = 'DEFAULT_VERANTWORTLICHER_TS' OR name = 'DEFAULT_VERANTWORTLICHER_BG';
