DELETE FROM ebegu_vorlage
WHERE name = 'VORLAGE_BRIEF_TAGESSTAETTE_SCHULKINDER';

DELETE FROM einstellung
WHERE einstellung_key = 'PARAM_MASSGEBENDES_EINKOMMEN_MIN';

DELETE FROM einstellung
WHERE einstellung_key = 'PARAM_MASSGEBENDES_EINKOMMEN_MAX';