ALTER TABLE einkommensverschlechterung_info DROP COLUMN stichtag_fuer_basis_jahr_plus1;
ALTER TABLE einkommensverschlechterung_info DROP COLUMN stichtag_fuer_basis_jahr_plus2;

ALTER TABLE einkommensverschlechterung_info DROP COLUMN grund_fuer_basis_jahr_plus1;
ALTER TABLE einkommensverschlechterung_info DROP COLUMN grund_fuer_basis_jahr_plus2;

ALTER TABLE einkommensverschlechterung_info_aud DROP COLUMN stichtag_fuer_basis_jahr_plus1;
ALTER TABLE einkommensverschlechterung_info_aud DROP COLUMN stichtag_fuer_basis_jahr_plus2;

ALTER TABLE einkommensverschlechterung_info_aud DROP COLUMN grund_fuer_basis_jahr_plus1;
ALTER TABLE einkommensverschlechterung_info_aud DROP COLUMN grund_fuer_basis_jahr_plus2;